spring:
  application:
    name: BookingCare
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    username: ${mail.user}
    password: ${mail.password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: error
