spring:
  application:
    name: BookingCare
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    username: ${mail.user}
    password: ${mail.password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${kafka.port}
#    security:
#      protocol: "SSL"
#    ssl:
#      trust-store-location: classpath:client.truststore.jks
#      trust-store-password: ${kafka.password}
#      key-store-location: classpath:client.keystore.p12
#      key-store-password: ${kafka.password}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: error
